name: likk_picker
description: Custom camera and gallery picker. 
version: 1.0.3
homepage: https://github.com/tranhuongk/likk_picker

environment:
  sdk: ">=2.13.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.9.1
  photo_manager: ^1.3.1
  uuid: ^3.0.4
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.1.2

flutter:
  uses-material-design: true

  fonts:
    - family: CustomIcons
      fonts:
        - asset: lib/assets/fonts/CustomIcons.ttf
    - family: ShapeIcons
      fonts:
        - asset: lib/assets/fonts/ShapeIcons.ttf